export const schema = `# -----------------------------------------------
# !!! THIS FILE WAS GENERATED BY TYPE-GRAPHQL !!!
# !!!   DO NOT MODIFY THIS FILE BY YOURSELF   !!!
# -----------------------------------------------

type Query {
  allScenes: [SceneModel!]!
  allZones: [ZoneModel!]!
  scene(id: String!): SceneModel
  zone(id: String!): ZoneModel
}

type SceneModel {
  id: ID!
}

type ZoneModel {
  id: ID!
  map: String!
  name: String!
  spritesheet: String!
}
`;
