export enum MessageStates {
  OPEN_SCHEMA = 'OPEN_SCHEMA',
  SAVE_STATE = 'STATE_STATE',
  RESTORE_STATE = 'RESTORE_STATE',
  SAVE_CONNECTION = 'SAVE_CONNECTION',
  EXPLORE_SCHEMA = 'EXPLORE_SCHEMA',
  IS_LOADING = 'IS_LOADING',
  ALERT = 'ALERT',
}
