name: CI

on:
  pull_request:

jobs:
  mergechecks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: git fetch origin master
      - name: asdf setup
        uses: asdf-vm/actions/setup@v1.1.0
      - name: asdf install
        run: |
          set -x
          asdf plugin add pnpm
          asdf plugin add nodejs
          asdf plugin add just https://github.com/heliumbrain/asdf-just
          asdf install

      - name: Get pnpm cache directory path
        id: pnpm-cache-dir-path
        run: echo "::set-output name=dir::$(pnpm store path)"

      - name: Cache node modules
        id: pnpm-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ${{ steps.pnpm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - run: pnpm install --frozen-lockfile
      - run: just nx affected --target=typecheck
      - run: just nx affected --target=lint
      - run: just nx affected --target=test -- --ci --reporters=default --reporters=jest-junit
        env:
          JEST_JUNIT_OUTPUT_DIR: reports
          JEST_JUNIT_OUTPUT_NAME: jest-junit.xml
          JEST_JUNIT_ANCESTOR_SEPARATOR: ' › '
          JEST_JUNIT_UNIQUE_OUTPUT_NAME: false
          JEST_JUNIT_SUITE_NAME: '{filepath}'
          JEST_JUNIT_CLASSNAME: '{classname}'
          JEST_JUNIT_TITLE: '{title}'

      - uses: actions/upload-artifact@v2 # upload test results
        if: success() || failure() # run this step even if previous step failed
        with:
          name: test-results
          path: jest-junit.xml
